# configuration for CI pipelines

stages:
    - main

# set common variables
.basic_config:
    tags:
        # force to run on darwin
        - darwin-slurm-shared

    variables:
        # proxy settings to reach gitlab
        http_proxy: "http://proxyout.lanl.gov:8080"
        https_proxy: "http://proxyout.lanl.gov:8080"
            # load submodules
        GIT_SUBMODULE_STRATEGY: recursive
            # slurm options
        SCHEDULER_PARAMETERS: "--nodes=1 --partition=general --qos=debug --constraint='cpu_family:broadwell|cpu_family:haswell'"

###############################################################################
# define configuration as products

.config_matrix:
    extends: .basic_config
    # define job matrix
    parallel:
        matrix:
            - COMPILER: [gcc/12.2.0]
              PARALLELIZATION: [serial, openmpi/4.1.5]
              PETSC: [petsc/3.20.1]
              ADIOS: [adios/2.9.2]
              BUILD_TYPE: [debug, release]
            - COMPILER: [gcc/10.4.0, gcc/11.3.0]
              PARALLELIZATION: [serial]
              PETSC: [none]
              ADIOS: [adios/2.9.2]
              BUILD_TYPE: [release]
            - COMPILER: [gcc/10.4.0, gcc/11.3.0]
              PARALLELIZATION: [openmpi/4.1.5]
              PETSC: [petsc/3.20.1]
              ADIOS: [adios/2.9.2]
              BUILD_TYPE: [release]
            - COMPILER: [gcc/11.2.0]
              PARALLELIZATION: [mpich/3.4.3]
              PETSC: [petsc/3.20.1]
              ADIOS: [adios/2.9.2]
              BUILD_TYPE: [release]

###############################################################################
# setup script

# These commands will run before each job.
before_script:
  - set -e
  - uname -a
  - |
    if [[ "$(uname)" = "Linux" ]]; then
      export THREADS=$(nproc --all)
    elif [[ "$(uname)" = "Darwin" ]]; then
      export THREADS=$(sysctl -n hw.ncpu)
    else
      echo "Unknown platform. Setting THREADS to 1."
      export THREADS=1
    fi

  # clone scripts
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lanl.gov/tbiifp/ifp-analysis.git scripts

  # load environment
  - source scripts/build/load_environment $COMPILER $BUILD_TYPE $PARALLELIZATION $ADIOS $PETSC
  # output modules for debuggin
  - module list
  # set path for build folder
  - build_path=build/$COMPILER/$PARALLELIZATION/$PETSC/$ADIOS/$TYPE/$BUILD_TYPE

###############################################################################
# script to build and test
# this has to be done in one step to avoid problems with the prefix paths
# of the parallel runners. CMake uses absolute paths, and if the configure
# runs on a different runner than the build/test, this will cause non-deterministic
# behavior and failurs

build:
    stage: main
    extends: .config_matrix
    script:
        - mkdir -p $build_path
        - cd $build_path
        - pwd
        - $CMAKE_COMMAND
        - make framework
        - ctest --output-on-failure
